# .github/DISCUSSION_TEMPLATE/general.yml
title: "[Discussion Topic]"
labels: ["discussion"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for starting a discussion in the shaduxe/ui community! Please fill out the information below to help guide the conversation.
  - type: dropdown
    id: discussion-type
    attributes:
      label: Discussion Type
      description: What kind of discussion are you starting?
      options:
        - Question (I need help with something)
        - Idea (I have a suggestion for shaduxe/ui)
        - Show and Tell (I want to share something I made with shaduxe/ui)
        - Other (General discussion or feedback)
    validations:
      required: true
  - type: textarea
    id: discussion-details
    attributes:
      label: Discussion Details
      description: Provide more information about your discussion topic.
      placeholder: |
        If it's a question: What are you trying to achieve? What have you tried so far?
        If it's an idea: What's your suggestion? How would it benefit the community?
        If it's a show and tell: What did you create? How did shaduxe/ui help you build it?
    validations:
      required: true
  - type: textarea
    id: code-example
    attributes:
      label: Code Example (if applicable)
      description: If your discussion involves code, please provide a minimal example.
      render: tsx
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this discussion, you agree to follow our [Code of Conduct](link-to-code-of-conduct)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
  - type: markdown
    attributes:
      value: |
        ## Tips for a Great Discussion
        - Be clear and concise in your topic
        - Provide context and examples where possible
        - Be respectful of others' opinions and ideas
        - Use code blocks for any code snippets
        - If sharing an idea, consider potential use cases or implementations
        - For questions, describe what you've already tried or researched
        
        Thank you for contributing to the shaduxe/ui community!
