// @ts-nocheck
// This file is autogenerated by scripts/build-registry.mts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "default": {
    "button": {
      name: "button",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/ui/button.tsx"],
      component: React.lazy(() => import("@/registry/default/ui/button.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "tabs": {
      name: "tabs",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/ui/tabs.tsx"],
      component: React.lazy(() => import("@/registry/default/ui/tabs.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "switch": {
      name: "switch",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/ui/switch.tsx"],
      component: React.lazy(() => import("@/registry/default/ui/switch.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "tabs-default-example": {
      name: "tabs-default-example",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/example/tabs-default-example.tsx"],
      component: React.lazy(() => import("@/registry/default/example/tabs-default-example.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "tabs-pill-example": {
      name: "tabs-pill-example",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/example/tabs-pill-example.tsx"],
      component: React.lazy(() => import("@/registry/default/example/tabs-pill-example.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "tabs-rounded-example": {
      name: "tabs-rounded-example",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/example/tabs-rounded-example.tsx"],
      component: React.lazy(() => import("@/registry/default/example/tabs-rounded-example.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "tabs-underline-example": {
      name: "tabs-underline-example",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/example/tabs-underline-example.tsx"],
      component: React.lazy(() => import("@/registry/default/example/tabs-underline-example.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "tabs-folder-example": {
      name: "tabs-folder-example",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/example/tabs-folder-example.tsx"],
      component: React.lazy(() => import("@/registry/default/example/tabs-folder-example.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "tabs-vertical-example": {
      name: "tabs-vertical-example",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/example/tabs-vertical-example.tsx"],
      component: React.lazy(() => import("@/registry/default/example/tabs-vertical-example.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "button-default-example": {
      name: "button-default-example",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/example/button-default-example.tsx"],
      component: React.lazy(() => import("@/registry/default/example/button-default-example.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "button-destructive-example": {
      name: "button-destructive-example",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/example/button-destructive-example.tsx"],
      component: React.lazy(() => import("@/registry/default/example/button-destructive-example.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "button-outline-example": {
      name: "button-outline-example",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/example/button-outline-example.tsx"],
      component: React.lazy(() => import("@/registry/default/example/button-outline-example.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "button-secondary-example": {
      name: "button-secondary-example",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/example/button-secondary-example.tsx"],
      component: React.lazy(() => import("@/registry/default/example/button-secondary-example.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "button-ghost-example": {
      name: "button-ghost-example",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/example/button-ghost-example.tsx"],
      component: React.lazy(() => import("@/registry/default/example/button-ghost-example.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "button-link-example": {
      name: "button-link-example",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/example/button-link-example.tsx"],
      component: React.lazy(() => import("@/registry/default/example/button-link-example.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "button-expand-icon-example": {
      name: "button-expand-icon-example",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/example/button-expand-icon-example.tsx"],
      component: React.lazy(() => import("@/registry/default/example/button-expand-icon-example.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "button-ring-hover-example": {
      name: "button-ring-hover-example",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/example/button-ring-hover-example.tsx"],
      component: React.lazy(() => import("@/registry/default/example/button-ring-hover-example.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "button-ring-hover-outline-example": {
      name: "button-ring-hover-outline-example",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/example/button-ring-hover-outline-example.tsx"],
      component: React.lazy(() => import("@/registry/default/example/button-ring-hover-outline-example.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "button-shine-example": {
      name: "button-shine-example",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/example/button-shine-example.tsx"],
      component: React.lazy(() => import("@/registry/default/example/button-shine-example.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "button-gooey-right-example": {
      name: "button-gooey-right-example",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/example/button-gooey-right-example.tsx"],
      component: React.lazy(() => import("@/registry/default/example/button-gooey-right-example.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "button-gooey-left-example": {
      name: "button-gooey-left-example",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/example/button-gooey-left-example.tsx"],
      component: React.lazy(() => import("@/registry/default/example/button-gooey-left-example.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "button-link-hover-1-example": {
      name: "button-link-hover-1-example",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/example/button-link-hover-1-example.tsx"],
      component: React.lazy(() => import("@/registry/default/example/button-link-hover-1-example.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "button-link-hover-2-example": {
      name: "button-link-hover-2-example",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/example/button-link-hover-2-example.tsx"],
      component: React.lazy(() => import("@/registry/default/example/button-link-hover-2-example.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "button-sm-example": {
      name: "button-sm-example",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/example/button-sm-example.tsx"],
      component: React.lazy(() => import("@/registry/default/example/button-sm-example.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "button-lg-example": {
      name: "button-lg-example",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/example/button-lg-example.tsx"],
      component: React.lazy(() => import("@/registry/default/example/button-lg-example.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "button-icon-example": {
      name: "button-icon-example",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/example/button-icon-example.tsx"],
      component: React.lazy(() => import("@/registry/default/example/button-icon-example.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "utils": {
      name: "utils",
      type: "registry:lib",
      registryDependencies: undefined,
      files: ["registry/default/lib/utils.ts"],
      component: React.lazy(() => import("@/registry/default/lib/utils.ts")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
  },
}
