// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.

import * as React from "react";

// Helper function to safely import components
const safeLazy = (importFn) => {
  return React.lazy(() =>
    importFn().catch((error) => {
      console.error("Failed to load component:", error);
      return {
        default: () =>
          React.createElement(
            "div",
            {
              style: {
                padding: "1rem",
                backgroundColor: "rgba(239, 68, 68, 0.1)",
                border: "1px solid rgba(239, 68, 68, 0.2)",
                borderRadius: "0.375rem",
                color: "rgb(185, 28, 28)",
                fontSize: "0.875rem",
              },
            },
            "Failed to load component",
          ),
      };
    }),
  );
};

export const Index: Record<string, any> = {
  default: {
    accordion: {
      name: "accordion",
      type: "registry:ui",
      registryDependencies: [],
      files: ["registry/default/ui/accordion.tsx"],
      component: safeLazy(() => import("@/registry/default/ui/accordion")),
      variants: {},
      source: "https://ui.shaduxe.com/r/styles/default/accordion.json",
      chunks: [],
    },
    alert: {
      name: "alert",
      type: "registry:ui",
      registryDependencies: [],
      files: ["registry/default/ui/alert.tsx"],
      component: safeLazy(() => import("@/registry/default/ui/alert")),
      variants: {},
      source: "https://ui.shaduxe.com/r/styles/default/alert.json",
      chunks: [],
    },
    avatar: {
      name: "avatar",
      type: "registry:ui",
      registryDependencies: [],
      files: ["registry/default/ui/avatar.tsx"],
      component: safeLazy(() => import("@/registry/default/ui/avatar")),
      variants: {},
      source: "https://ui.shaduxe.com/r/styles/default/avatar.json",
      chunks: [],
    },
    badge: {
      name: "badge",
      type: "registry:ui",
      registryDependencies: [],
      files: ["registry/default/ui/badge.tsx"],
      component: safeLazy(() => import("@/registry/default/ui/badge")),
      variants: {},
      source: "https://ui.shaduxe.com/r/styles/default/badge.json",
      chunks: [],
    },
    button: {
      name: "button",
      type: "registry:ui",
      registryDependencies: [],
      files: ["registry/default/ui/button.tsx"],
      component: safeLazy(() => import("@/registry/default/ui/button")),
      variants: {},
      source: "https://ui.shaduxe.com/r/styles/default/button.json",
      chunks: [],
    },
    card: {
      name: "card",
      type: "registry:ui",
      registryDependencies: [],
      files: ["registry/default/ui/card.tsx"],
      component: safeLazy(() => import("@/registry/default/ui/card")),
      variants: {},
      source: "https://ui.shaduxe.com/r/styles/default/card.json",
      chunks: [],
    },
    input: {
      name: "input",
      type: "registry:ui",
      registryDependencies: [],
      files: ["registry/default/ui/input.tsx"],
      component: safeLazy(() => import("@/registry/default/ui/input")),
      variants: {},
      source: "https://ui.shaduxe.com/r/styles/default/input.json",
      chunks: [],
    },
    "mode-toggle": {
      name: "mode-toggle",
      type: "registry:ui",
      registryDependencies: ["button"],
      files: ["registry/default/ui/mode-toggle.tsx"],
      component: safeLazy(() => import("@/registry/default/ui/mode-toggle")),
      variants: {},
      source: "https://ui.shaduxe.com/r/styles/default/mode-toggle.json",
      chunks: [],
    },
    switch: {
      name: "switch",
      type: "registry:ui",
      registryDependencies: [],
      files: ["registry/default/ui/switch.tsx"],
      component: safeLazy(() => import("@/registry/default/ui/switch")),
      variants: {},
      source: "https://ui.shaduxe.com/r/styles/default/switch.json",
      chunks: [],
    },
    tabs: {
      name: "tabs",
      type: "registry:ui",
      registryDependencies: [],
      files: ["registry/default/ui/tabs.tsx"],
      component: safeLazy(() => import("@/registry/default/ui/tabs")),
      variants: {},
      source: "https://ui.shaduxe.com/r/styles/default/tabs.json",
      chunks: [],
    },
    "accordion-demo": {
      name: "accordion-demo",
      type: "registry:ui",
      registryDependencies: ["accordion"],
      files: ["registry/default/example/accordion-demo.tsx"],
      component: safeLazy(() =>
        import("@/registry/default/example/accordion-demo").then((mod) => {
          // For demo components, try to use default export first, then specific demo component
          if (mod.default) {
            return { default: mod.default };
          } else if (mod.AccordionDemo) {
            return { default: mod.AccordionDemo };
          } else {
            console.error(
              "Could not find default export or demo export in @/registry/default/example/accordion-demo",
            );
            return {
              default: () =>
                React.createElement(
                  "div",
                  {
                    className:
                      "p-4 text-red-500 bg-red-50 border border-red-100 rounded",
                  },
                  "Component failed to load",
                ),
            };
          }
        }),
      ),
      variants: {
        demo: {
          name: "demo",
          description: "demo variant of accordion",
          component: safeLazy(() =>
            import("@/registry/default/example/accordion-demo").then((mod) => {
              if (mod.AccordionDemo) {
                return { default: mod.AccordionDemo };
              } else {
                console.error(
                  "Variant component AccordionDemo not found in @/registry/default/example/accordion-demo",
                );
                return {
                  default: () =>
                    React.createElement(
                      "div",
                      {
                        className:
                          "p-4 text-red-500 bg-red-50 border border-red-100 rounded",
                      },
                      "Variant demo not found",
                    ),
                };
              }
            }),
          ),
        },
        variants: {
          name: "variants",
          description: "variants variant of accordion",
          component: safeLazy(() =>
            import("@/registry/default/example/accordion-demo").then((mod) => {
              if (mod.AccordionVariants) {
                return { default: mod.AccordionVariants };
              } else {
                console.error(
                  "Variant component AccordionVariants not found in @/registry/default/example/accordion-demo",
                );
                return {
                  default: () =>
                    React.createElement(
                      "div",
                      {
                        className:
                          "p-4 text-red-500 bg-red-50 border border-red-100 rounded",
                      },
                      "Variant variants not found",
                    ),
                };
              }
            }),
          ),
        },
        multiple: {
          name: "multiple",
          description: "multiple variant of accordion",
          component: safeLazy(() =>
            import("@/registry/default/example/accordion-demo").then((mod) => {
              if (mod.AccordionMultiple) {
                return { default: mod.AccordionMultiple };
              } else {
                console.error(
                  "Variant component AccordionMultiple not found in @/registry/default/example/accordion-demo",
                );
                return {
                  default: () =>
                    React.createElement(
                      "div",
                      {
                        className:
                          "p-4 text-red-500 bg-red-50 border border-red-100 rounded",
                      },
                      "Variant multiple not found",
                    ),
                };
              }
            }),
          ),
        },
        iconPosition: {
          name: "iconPosition",
          description: "iconPosition variant of accordion",
          component: safeLazy(() =>
            import("@/registry/default/example/accordion-demo").then((mod) => {
              if (mod.AccordionIconPosition) {
                return { default: mod.AccordionIconPosition };
              } else {
                console.error(
                  "Variant component AccordionIconPosition not found in @/registry/default/example/accordion-demo",
                );
                return {
                  default: () =>
                    React.createElement(
                      "div",
                      {
                        className:
                          "p-4 text-red-500 bg-red-50 border border-red-100 rounded",
                      },
                      "Variant iconPosition not found",
                    ),
                };
              }
            }),
          ),
        },
        customIcons: {
          name: "customIcons",
          description: "customIcons variant of accordion",
          component: safeLazy(() =>
            import("@/registry/default/example/accordion-demo").then((mod) => {
              if (mod.AccordionCustomIcons) {
                return { default: mod.AccordionCustomIcons };
              } else {
                console.error(
                  "Variant component AccordionCustomIcons not found in @/registry/default/example/accordion-demo",
                );
                return {
                  default: () =>
                    React.createElement(
                      "div",
                      {
                        className:
                          "p-4 text-red-500 bg-red-50 border border-red-100 rounded",
                      },
                      "Variant customIcons not found",
                    ),
                };
              }
            }),
          ),
        },
        animations: {
          name: "animations",
          description: "animations variant of accordion",
          component: safeLazy(() =>
            import("@/registry/default/example/accordion-demo").then((mod) => {
              if (mod.AccordionAnimations) {
                return { default: mod.AccordionAnimations };
              } else {
                console.error(
                  "Variant component AccordionAnimations not found in @/registry/default/example/accordion-demo",
                );
                return {
                  default: () =>
                    React.createElement(
                      "div",
                      {
                        className:
                          "p-4 text-red-500 bg-red-50 border border-red-100 rounded",
                      },
                      "Variant animations not found",
                    ),
                };
              }
            }),
          ),
        },
      },
      source: "https://ui.shaduxe.com/r/styles/default/accordion-demo.json",
      chunks: [],
    },
    "alert-demo": {
      name: "alert-demo",
      type: "registry:ui",
      registryDependencies: ["alert"],
      files: ["registry/default/example/alert-demo.tsx"],
      component: safeLazy(() =>
        import("@/registry/default/example/alert-demo").then((mod) => {
          // For demo components, try to use default export first, then specific demo component
          if (mod.default) {
            return { default: mod.default };
          } else if (mod.AlertDemo) {
            return { default: mod.AlertDemo };
          } else {
            console.error(
              "Could not find default export or demo export in @/registry/default/example/alert-demo",
            );
            return {
              default: () =>
                React.createElement(
                  "div",
                  {
                    className:
                      "p-4 text-red-500 bg-red-50 border border-red-100 rounded",
                  },
                  "Component failed to load",
                ),
            };
          }
        }),
      ),
      variants: {
        demo: {
          name: "demo",
          description: "demo variant of alert",
          component: safeLazy(() =>
            import("@/registry/default/example/alert-demo").then((mod) => {
              if (mod.AlertDemo) {
                return { default: mod.AlertDemo };
              } else {
                console.error(
                  "Variant component AlertDemo not found in @/registry/default/example/alert-demo",
                );
                return {
                  default: () =>
                    React.createElement(
                      "div",
                      {
                        className:
                          "p-4 text-red-500 bg-red-50 border border-red-100 rounded",
                      },
                      "Variant demo not found",
                    ),
                };
              }
            }),
          ),
        },
        variants: {
          name: "variants",
          description: "variants variant of alert",
          component: safeLazy(() =>
            import("@/registry/default/example/alert-demo").then((mod) => {
              if (mod.AlertVariants) {
                return { default: mod.AlertVariants };
              } else {
                console.error(
                  "Variant component AlertVariants not found in @/registry/default/example/alert-demo",
                );
                return {
                  default: () =>
                    React.createElement(
                      "div",
                      {
                        className:
                          "p-4 text-red-500 bg-red-50 border border-red-100 rounded",
                      },
                      "Variant variants not found",
                    ),
                };
              }
            }),
          ),
        },
        sizes: {
          name: "sizes",
          description: "sizes variant of alert",
          component: safeLazy(() =>
            import("@/registry/default/example/alert-demo").then((mod) => {
              if (mod.AlertSizes) {
                return { default: mod.AlertSizes };
              } else {
                console.error(
                  "Variant component AlertSizes not found in @/registry/default/example/alert-demo",
                );
                return {
                  default: () =>
                    React.createElement(
                      "div",
                      {
                        className:
                          "p-4 text-red-500 bg-red-50 border border-red-100 rounded",
                      },
                      "Variant sizes not found",
                    ),
                };
              }
            }),
          ),
        },
        withoutIcon: {
          name: "withoutIcon",
          description: "withoutIcon variant of alert",
          component: safeLazy(() =>
            import("@/registry/default/example/alert-demo").then((mod) => {
              if (mod.AlertWithoutIcon) {
                return { default: mod.AlertWithoutIcon };
              } else {
                console.error(
                  "Variant component AlertWithoutIcon not found in @/registry/default/example/alert-demo",
                );
                return {
                  default: () =>
                    React.createElement(
                      "div",
                      {
                        className:
                          "p-4 text-red-500 bg-red-50 border border-red-100 rounded",
                      },
                      "Variant withoutIcon not found",
                    ),
                };
              }
            }),
          ),
        },
      },
      source: "https://ui.shaduxe.com/r/styles/default/alert-demo.json",
      chunks: [],
    },
    "avatar-demo": {
      name: "avatar-demo",
      type: "registry:ui",
      registryDependencies: ["avatar"],
      files: ["registry/default/example/avatar-demo.tsx"],
      component: safeLazy(() =>
        import("@/registry/default/example/avatar-demo").then((mod) => {
          // For demo components, try to use default export first, then specific demo component
          if (mod.default) {
            return { default: mod.default };
          } else if (mod.AvatarDemo) {
            return { default: mod.AvatarDemo };
          } else {
            console.error(
              "Could not find default export or demo export in @/registry/default/example/avatar-demo",
            );
            return {
              default: () =>
                React.createElement(
                  "div",
                  {
                    className:
                      "p-4 text-red-500 bg-red-50 border border-red-100 rounded",
                  },
                  "Component failed to load",
                ),
            };
          }
        }),
      ),
      variants: {
        demo: {
          name: "demo",
          description: "demo variant of avatar",
          component: safeLazy(() =>
            import("@/registry/default/example/avatar-demo").then((mod) => {
              if (mod.AvatarDemo) {
                return { default: mod.AvatarDemo };
              } else {
                console.error(
                  "Variant component AvatarDemo not found in @/registry/default/example/avatar-demo",
                );
                return {
                  default: () =>
                    React.createElement(
                      "div",
                      {
                        className:
                          "p-4 text-red-500 bg-red-50 border border-red-100 rounded",
                      },
                      "Variant demo not found",
                    ),
                };
              }
            }),
          ),
        },
        variants: {
          name: "variants",
          description: "variants variant of avatar",
          component: safeLazy(() =>
            import("@/registry/default/example/avatar-demo").then((mod) => {
              if (mod.AvatarVariants) {
                return { default: mod.AvatarVariants };
              } else {
                console.error(
                  "Variant component AvatarVariants not found in @/registry/default/example/avatar-demo",
                );
                return {
                  default: () =>
                    React.createElement(
                      "div",
                      {
                        className:
                          "p-4 text-red-500 bg-red-50 border border-red-100 rounded",
                      },
                      "Variant variants not found",
                    ),
                };
              }
            }),
          ),
        },
        circle: {
          name: "circle",
          description: "circle variant of avatar",
          component: safeLazy(() =>
            import("@/registry/default/example/avatar-demo").then((mod) => {
              if (mod.AvatarCircle) {
                return { default: mod.AvatarCircle };
              } else {
                console.error(
                  "Variant component AvatarCircle not found in @/registry/default/example/avatar-demo",
                );
                return {
                  default: () =>
                    React.createElement(
                      "div",
                      {
                        className:
                          "p-4 text-red-500 bg-red-50 border border-red-100 rounded",
                      },
                      "Variant circle not found",
                    ),
                };
              }
            }),
          ),
        },
        square: {
          name: "square",
          description: "square variant of avatar",
          component: safeLazy(() =>
            import("@/registry/default/example/avatar-demo").then((mod) => {
              if (mod.AvatarSquare) {
                return { default: mod.AvatarSquare };
              } else {
                console.error(
                  "Variant component AvatarSquare not found in @/registry/default/example/avatar-demo",
                );
                return {
                  default: () =>
                    React.createElement(
                      "div",
                      {
                        className:
                          "p-4 text-red-500 bg-red-50 border border-red-100 rounded",
                      },
                      "Variant square not found",
                    ),
                };
              }
            }),
          ),
        },
        rounded: {
          name: "rounded",
          description: "rounded variant of avatar",
          component: safeLazy(() =>
            import("@/registry/default/example/avatar-demo").then((mod) => {
              if (mod.AvatarRounded) {
                return { default: mod.AvatarRounded };
              } else {
                console.error(
                  "Variant component AvatarRounded not found in @/registry/default/example/avatar-demo",
                );
                return {
                  default: () =>
                    React.createElement(
                      "div",
                      {
                        className:
                          "p-4 text-red-500 bg-red-50 border border-red-100 rounded",
                      },
                      "Variant rounded not found",
                    ),
                };
              }
            }),
          ),
        },
        withFallback: {
          name: "withFallback",
          description: "withFallback variant of avatar",
          component: safeLazy(() =>
            import("@/registry/default/example/avatar-demo").then((mod) => {
              if (mod.AvatarWithFallback) {
                return { default: mod.AvatarWithFallback };
              } else {
                console.error(
                  "Variant component AvatarWithFallback not found in @/registry/default/example/avatar-demo",
                );
                return {
                  default: () =>
                    React.createElement(
                      "div",
                      {
                        className:
                          "p-4 text-red-500 bg-red-50 border border-red-100 rounded",
                      },
                      "Variant withFallback not found",
                    ),
                };
              }
            }),
          ),
        },
      },
      source: "https://ui.shaduxe.com/r/styles/default/avatar-demo.json",
      chunks: [],
    },
    "badge-demo": {
      name: "badge-demo",
      type: "registry:ui",
      registryDependencies: ["badge"],
      files: ["registry/default/example/badge-demo.tsx"],
      component: safeLazy(() =>
        import("@/registry/default/example/badge-demo").then((mod) => {
          // For demo components, try to use default export first, then specific demo component
          if (mod.default) {
            return { default: mod.default };
          } else if (mod.BadgeDemo) {
            return { default: mod.BadgeDemo };
          } else {
            console.error(
              "Could not find default export or demo export in @/registry/default/example/badge-demo",
            );
            return {
              default: () =>
                React.createElement(
                  "div",
                  {
                    className:
                      "p-4 text-red-500 bg-red-50 border border-red-100 rounded",
                  },
                  "Component failed to load",
                ),
            };
          }
        }),
      ),
      variants: {
        demo: {
          name: "demo",
          description: "demo variant of badge",
          component: safeLazy(() =>
            import("@/registry/default/example/badge-demo").then((mod) => {
              if (mod.BadgeDemo) {
                return { default: mod.BadgeDemo };
              } else {
                console.error(
                  "Variant component BadgeDemo not found in @/registry/default/example/badge-demo",
                );
                return {
                  default: () =>
                    React.createElement(
                      "div",
                      {
                        className:
                          "p-4 text-red-500 bg-red-50 border border-red-100 rounded",
                      },
                      "Variant demo not found",
                    ),
                };
              }
            }),
          ),
        },
        variants: {
          name: "variants",
          description: "variants variant of badge",
          component: safeLazy(() =>
            import("@/registry/default/example/badge-demo").then((mod) => {
              if (mod.BadgeVariants) {
                return { default: mod.BadgeVariants };
              } else {
                console.error(
                  "Variant component BadgeVariants not found in @/registry/default/example/badge-demo",
                );
                return {
                  default: () =>
                    React.createElement(
                      "div",
                      {
                        className:
                          "p-4 text-red-500 bg-red-50 border border-red-100 rounded",
                      },
                      "Variant variants not found",
                    ),
                };
              }
            }),
          ),
        },
        default: {
          name: "default",
          description: "default variant of badge",
          component: safeLazy(() =>
            import("@/registry/default/example/badge-demo").then((mod) => {
              if (mod.BadgeDefault) {
                return { default: mod.BadgeDefault };
              } else {
                console.error(
                  "Variant component BadgeDefault not found in @/registry/default/example/badge-demo",
                );
                return {
                  default: () =>
                    React.createElement(
                      "div",
                      {
                        className:
                          "p-4 text-red-500 bg-red-50 border border-red-100 rounded",
                      },
                      "Variant default not found",
                    ),
                };
              }
            }),
          ),
        },
        secondary: {
          name: "secondary",
          description: "secondary variant of badge",
          component: safeLazy(() =>
            import("@/registry/default/example/badge-demo").then((mod) => {
              if (mod.BadgeSecondary) {
                return { default: mod.BadgeSecondary };
              } else {
                console.error(
                  "Variant component BadgeSecondary not found in @/registry/default/example/badge-demo",
                );
                return {
                  default: () =>
                    React.createElement(
                      "div",
                      {
                        className:
                          "p-4 text-red-500 bg-red-50 border border-red-100 rounded",
                      },
                      "Variant secondary not found",
                    ),
                };
              }
            }),
          ),
        },
        destructive: {
          name: "destructive",
          description: "destructive variant of badge",
          component: safeLazy(() =>
            import("@/registry/default/example/badge-demo").then((mod) => {
              if (mod.BadgeDestructive) {
                return { default: mod.BadgeDestructive };
              } else {
                console.error(
                  "Variant component BadgeDestructive not found in @/registry/default/example/badge-demo",
                );
                return {
                  default: () =>
                    React.createElement(
                      "div",
                      {
                        className:
                          "p-4 text-red-500 bg-red-50 border border-red-100 rounded",
                      },
                      "Variant destructive not found",
                    ),
                };
              }
            }),
          ),
        },
        outline: {
          name: "outline",
          description: "outline variant of badge",
          component: safeLazy(() =>
            import("@/registry/default/example/badge-demo").then((mod) => {
              if (mod.BadgeOutline) {
                return { default: mod.BadgeOutline };
              } else {
                console.error(
                  "Variant component BadgeOutline not found in @/registry/default/example/badge-demo",
                );
                return {
                  default: () =>
                    React.createElement(
                      "div",
                      {
                        className:
                          "p-4 text-red-500 bg-red-50 border border-red-100 rounded",
                      },
                      "Variant outline not found",
                    ),
                };
              }
            }),
          ),
        },
        ghost: {
          name: "ghost",
          description: "ghost variant of badge",
          component: safeLazy(() =>
            import("@/registry/default/example/badge-demo").then((mod) => {
              if (mod.BadgeGhost) {
                return { default: mod.BadgeGhost };
              } else {
                console.error(
                  "Variant component BadgeGhost not found in @/registry/default/example/badge-demo",
                );
                return {
                  default: () =>
                    React.createElement(
                      "div",
                      {
                        className:
                          "p-4 text-red-500 bg-red-50 border border-red-100 rounded",
                      },
                      "Variant ghost not found",
                    ),
                };
              }
            }),
          ),
        },
        link: {
          name: "link",
          description: "link variant of badge",
          component: safeLazy(() =>
            import("@/registry/default/example/badge-demo").then((mod) => {
              if (mod.BadgeLink) {
                return { default: mod.BadgeLink };
              } else {
                console.error(
                  "Variant component BadgeLink not found in @/registry/default/example/badge-demo",
                );
                return {
                  default: () =>
                    React.createElement(
                      "div",
                      {
                        className:
                          "p-4 text-red-500 bg-red-50 border border-red-100 rounded",
                      },
                      "Variant link not found",
                    ),
                };
              }
            }),
          ),
        },
        success: {
          name: "success",
          description: "success variant of badge",
          component: safeLazy(() =>
            import("@/registry/default/example/badge-demo").then((mod) => {
              if (mod.BadgeSuccess) {
                return { default: mod.BadgeSuccess };
              } else {
                console.error(
                  "Variant component BadgeSuccess not found in @/registry/default/example/badge-demo",
                );
                return {
                  default: () =>
                    React.createElement(
                      "div",
                      {
                        className:
                          "p-4 text-red-500 bg-red-50 border border-red-100 rounded",
                      },
                      "Variant success not found",
                    ),
                };
              }
            }),
          ),
        },
        warning: {
          name: "warning",
          description: "warning variant of badge",
          component: safeLazy(() =>
            import("@/registry/default/example/badge-demo").then((mod) => {
              if (mod.BadgeWarning) {
                return { default: mod.BadgeWarning };
              } else {
                console.error(
                  "Variant component BadgeWarning not found in @/registry/default/example/badge-demo",
                );
                return {
                  default: () =>
                    React.createElement(
                      "div",
                      {
                        className:
                          "p-4 text-red-500 bg-red-50 border border-red-100 rounded",
                      },
                      "Variant warning not found",
                    ),
                };
              }
            }),
          ),
        },
        info: {
          name: "info",
          description: "info variant of badge",
          component: safeLazy(() =>
            import("@/registry/default/example/badge-demo").then((mod) => {
              if (mod.BadgeInfo) {
                return { default: mod.BadgeInfo };
              } else {
                console.error(
                  "Variant component BadgeInfo not found in @/registry/default/example/badge-demo",
                );
                return {
                  default: () =>
                    React.createElement(
                      "div",
                      {
                        className:
                          "p-4 text-red-500 bg-red-50 border border-red-100 rounded",
                      },
                      "Variant info not found",
                    ),
                };
              }
            }),
          ),
        },
      },
      source: "https://ui.shaduxe.com/r/styles/default/badge-demo.json",
      chunks: [],
    },
    "button-demo": {
      name: "button-demo",
      type: "registry:ui",
      registryDependencies: ["button"],
      files: ["registry/default/example/button-demo.tsx"],
      component: safeLazy(() =>
        import("@/registry/default/example/button-demo").then((mod) => {
          // For demo components, try to use default export first, then specific demo component
          if (mod.default) {
            return { default: mod.default };
          } else if (mod.ButtonDemo) {
            return { default: mod.ButtonDemo };
          } else {
            console.error(
              "Could not find default export or demo export in @/registry/default/example/button-demo",
            );
            return {
              default: () =>
                React.createElement(
                  "div",
                  {
                    className:
                      "p-4 text-red-500 bg-red-50 border border-red-100 rounded",
                  },
                  "Component failed to load",
                ),
            };
          }
        }),
      ),
      variants: {
        demo: {
          name: "demo",
          description: "demo variant of button",
          component: safeLazy(() =>
            import("@/registry/default/example/button-demo").then((mod) => {
              if (mod.ButtonDemo) {
                return { default: mod.ButtonDemo };
              } else {
                console.error(
                  "Variant component ButtonDemo not found in @/registry/default/example/button-demo",
                );
                return {
                  default: () =>
                    React.createElement(
                      "div",
                      {
                        className:
                          "p-4 text-red-500 bg-red-50 border border-red-100 rounded",
                      },
                      "Variant demo not found",
                    ),
                };
              }
            }),
          ),
        },
        variants: {
          name: "variants",
          description: "variants variant of button",
          component: safeLazy(() =>
            import("@/registry/default/example/button-demo").then((mod) => {
              if (mod.ButtonVariants) {
                return { default: mod.ButtonVariants };
              } else {
                console.error(
                  "Variant component ButtonVariants not found in @/registry/default/example/button-demo",
                );
                return {
                  default: () =>
                    React.createElement(
                      "div",
                      {
                        className:
                          "p-4 text-red-500 bg-red-50 border border-red-100 rounded",
                      },
                      "Variant variants not found",
                    ),
                };
              }
            }),
          ),
        },
        default: {
          name: "default",
          description: "default variant of button",
          component: safeLazy(() =>
            import("@/registry/default/example/button-demo").then((mod) => {
              if (mod.ButtonDefault) {
                return { default: mod.ButtonDefault };
              } else {
                console.error(
                  "Variant component ButtonDefault not found in @/registry/default/example/button-demo",
                );
                return {
                  default: () =>
                    React.createElement(
                      "div",
                      {
                        className:
                          "p-4 text-red-500 bg-red-50 border border-red-100 rounded",
                      },
                      "Variant default not found",
                    ),
                };
              }
            }),
          ),
        },
        destructive: {
          name: "destructive",
          description: "destructive variant of button",
          component: safeLazy(() =>
            import("@/registry/default/example/button-demo").then((mod) => {
              if (mod.ButtonDestructive) {
                return { default: mod.ButtonDestructive };
              } else {
                console.error(
                  "Variant component ButtonDestructive not found in @/registry/default/example/button-demo",
                );
                return {
                  default: () =>
                    React.createElement(
                      "div",
                      {
                        className:
                          "p-4 text-red-500 bg-red-50 border border-red-100 rounded",
                      },
                      "Variant destructive not found",
                    ),
                };
              }
            }),
          ),
        },
        outline: {
          name: "outline",
          description: "outline variant of button",
          component: safeLazy(() =>
            import("@/registry/default/example/button-demo").then((mod) => {
              if (mod.ButtonOutline) {
                return { default: mod.ButtonOutline };
              } else {
                console.error(
                  "Variant component ButtonOutline not found in @/registry/default/example/button-demo",
                );
                return {
                  default: () =>
                    React.createElement(
                      "div",
                      {
                        className:
                          "p-4 text-red-500 bg-red-50 border border-red-100 rounded",
                      },
                      "Variant outline not found",
                    ),
                };
              }
            }),
          ),
        },
        secondary: {
          name: "secondary",
          description: "secondary variant of button",
          component: safeLazy(() =>
            import("@/registry/default/example/button-demo").then((mod) => {
              if (mod.ButtonSecondary) {
                return { default: mod.ButtonSecondary };
              } else {
                console.error(
                  "Variant component ButtonSecondary not found in @/registry/default/example/button-demo",
                );
                return {
                  default: () =>
                    React.createElement(
                      "div",
                      {
                        className:
                          "p-4 text-red-500 bg-red-50 border border-red-100 rounded",
                      },
                      "Variant secondary not found",
                    ),
                };
              }
            }),
          ),
        },
        ghost: {
          name: "ghost",
          description: "ghost variant of button",
          component: safeLazy(() =>
            import("@/registry/default/example/button-demo").then((mod) => {
              if (mod.ButtonGhost) {
                return { default: mod.ButtonGhost };
              } else {
                console.error(
                  "Variant component ButtonGhost not found in @/registry/default/example/button-demo",
                );
                return {
                  default: () =>
                    React.createElement(
                      "div",
                      {
                        className:
                          "p-4 text-red-500 bg-red-50 border border-red-100 rounded",
                      },
                      "Variant ghost not found",
                    ),
                };
              }
            }),
          ),
        },
        link: {
          name: "link",
          description: "link variant of button",
          component: safeLazy(() =>
            import("@/registry/default/example/button-demo").then((mod) => {
              if (mod.ButtonLink) {
                return { default: mod.ButtonLink };
              } else {
                console.error(
                  "Variant component ButtonLink not found in @/registry/default/example/button-demo",
                );
                return {
                  default: () =>
                    React.createElement(
                      "div",
                      {
                        className:
                          "p-4 text-red-500 bg-red-50 border border-red-100 rounded",
                      },
                      "Variant link not found",
                    ),
                };
              }
            }),
          ),
        },
        ringHover: {
          name: "ringHover",
          description: "ringHover variant of button",
          component: safeLazy(() =>
            import("@/registry/default/example/button-demo").then((mod) => {
              if (mod.ButtonRingHover) {
                return { default: mod.ButtonRingHover };
              } else {
                console.error(
                  "Variant component ButtonRingHover not found in @/registry/default/example/button-demo",
                );
                return {
                  default: () =>
                    React.createElement(
                      "div",
                      {
                        className:
                          "p-4 text-red-500 bg-red-50 border border-red-100 rounded",
                      },
                      "Variant ringHover not found",
                    ),
                };
              }
            }),
          ),
        },
        ringHoverOutline: {
          name: "ringHoverOutline",
          description: "ringHoverOutline variant of button",
          component: safeLazy(() =>
            import("@/registry/default/example/button-demo").then((mod) => {
              if (mod.ButtonRingHoverOutline) {
                return { default: mod.ButtonRingHoverOutline };
              } else {
                console.error(
                  "Variant component ButtonRingHoverOutline not found in @/registry/default/example/button-demo",
                );
                return {
                  default: () =>
                    React.createElement(
                      "div",
                      {
                        className:
                          "p-4 text-red-500 bg-red-50 border border-red-100 rounded",
                      },
                      "Variant ringHoverOutline not found",
                    ),
                };
              }
            }),
          ),
        },
        shine: {
          name: "shine",
          description: "shine variant of button",
          component: safeLazy(() =>
            import("@/registry/default/example/button-demo").then((mod) => {
              if (mod.ButtonShine) {
                return { default: mod.ButtonShine };
              } else {
                console.error(
                  "Variant component ButtonShine not found in @/registry/default/example/button-demo",
                );
                return {
                  default: () =>
                    React.createElement(
                      "div",
                      {
                        className:
                          "p-4 text-red-500 bg-red-50 border border-red-100 rounded",
                      },
                      "Variant shine not found",
                    ),
                };
              }
            }),
          ),
        },
        gooeyRight: {
          name: "gooeyRight",
          description: "gooeyRight variant of button",
          component: safeLazy(() =>
            import("@/registry/default/example/button-demo").then((mod) => {
              if (mod.ButtonGooeyRight) {
                return { default: mod.ButtonGooeyRight };
              } else {
                console.error(
                  "Variant component ButtonGooeyRight not found in @/registry/default/example/button-demo",
                );
                return {
                  default: () =>
                    React.createElement(
                      "div",
                      {
                        className:
                          "p-4 text-red-500 bg-red-50 border border-red-100 rounded",
                      },
                      "Variant gooeyRight not found",
                    ),
                };
              }
            }),
          ),
        },
        gooeyLeft: {
          name: "gooeyLeft",
          description: "gooeyLeft variant of button",
          component: safeLazy(() =>
            import("@/registry/default/example/button-demo").then((mod) => {
              if (mod.ButtonGooeyLeft) {
                return { default: mod.ButtonGooeyLeft };
              } else {
                console.error(
                  "Variant component ButtonGooeyLeft not found in @/registry/default/example/button-demo",
                );
                return {
                  default: () =>
                    React.createElement(
                      "div",
                      {
                        className:
                          "p-4 text-red-500 bg-red-50 border border-red-100 rounded",
                      },
                      "Variant gooeyLeft not found",
                    ),
                };
              }
            }),
          ),
        },
        underline: {
          name: "underline",
          description: "underline variant of button",
          component: safeLazy(() =>
            import("@/registry/default/example/button-demo").then((mod) => {
              if (mod.ButtonUnderline) {
                return { default: mod.ButtonUnderline };
              } else {
                console.error(
                  "Variant component ButtonUnderline not found in @/registry/default/example/button-demo",
                );
                return {
                  default: () =>
                    React.createElement(
                      "div",
                      {
                        className:
                          "p-4 text-red-500 bg-red-50 border border-red-100 rounded",
                      },
                      "Variant underline not found",
                    ),
                };
              }
            }),
          ),
        },
        hoverUnderline: {
          name: "hoverUnderline",
          description: "hoverUnderline variant of button",
          component: safeLazy(() =>
            import("@/registry/default/example/button-demo").then((mod) => {
              if (mod.ButtonHoverUnderline) {
                return { default: mod.ButtonHoverUnderline };
              } else {
                console.error(
                  "Variant component ButtonHoverUnderline not found in @/registry/default/example/button-demo",
                );
                return {
                  default: () =>
                    React.createElement(
                      "div",
                      {
                        className:
                          "p-4 text-red-500 bg-red-50 border border-red-100 rounded",
                      },
                      "Variant hoverUnderline not found",
                    ),
                };
              }
            }),
          ),
        },
        iconLeft: {
          name: "iconLeft",
          description: "iconLeft variant of button",
          component: safeLazy(() =>
            import("@/registry/default/example/button-demo").then((mod) => {
              if (mod.ButtonIconLeft) {
                return { default: mod.ButtonIconLeft };
              } else {
                console.error(
                  "Variant component ButtonIconLeft not found in @/registry/default/example/button-demo",
                );
                return {
                  default: () =>
                    React.createElement(
                      "div",
                      {
                        className:
                          "p-4 text-red-500 bg-red-50 border border-red-100 rounded",
                      },
                      "Variant iconLeft not found",
                    ),
                };
              }
            }),
          ),
        },
        iconRight: {
          name: "iconRight",
          description: "iconRight variant of button",
          component: safeLazy(() =>
            import("@/registry/default/example/button-demo").then((mod) => {
              if (mod.ButtonIconRight) {
                return { default: mod.ButtonIconRight };
              } else {
                console.error(
                  "Variant component ButtonIconRight not found in @/registry/default/example/button-demo",
                );
                return {
                  default: () =>
                    React.createElement(
                      "div",
                      {
                        className:
                          "p-4 text-red-500 bg-red-50 border border-red-100 rounded",
                      },
                      "Variant iconRight not found",
                    ),
                };
              }
            }),
          ),
        },
        expandIconLeft: {
          name: "expandIconLeft",
          description: "expandIconLeft variant of button",
          component: safeLazy(() =>
            import("@/registry/default/example/button-demo").then((mod) => {
              if (mod.ButtonExpandIconLeft) {
                return { default: mod.ButtonExpandIconLeft };
              } else {
                console.error(
                  "Variant component ButtonExpandIconLeft not found in @/registry/default/example/button-demo",
                );
                return {
                  default: () =>
                    React.createElement(
                      "div",
                      {
                        className:
                          "p-4 text-red-500 bg-red-50 border border-red-100 rounded",
                      },
                      "Variant expandIconLeft not found",
                    ),
                };
              }
            }),
          ),
        },
        expandIconRight: {
          name: "expandIconRight",
          description: "expandIconRight variant of button",
          component: safeLazy(() =>
            import("@/registry/default/example/button-demo").then((mod) => {
              if (mod.ButtonExpandIconRight) {
                return { default: mod.ButtonExpandIconRight };
              } else {
                console.error(
                  "Variant component ButtonExpandIconRight not found in @/registry/default/example/button-demo",
                );
                return {
                  default: () =>
                    React.createElement(
                      "div",
                      {
                        className:
                          "p-4 text-red-500 bg-red-50 border border-red-100 rounded",
                      },
                      "Variant expandIconRight not found",
                    ),
                };
              }
            }),
          ),
        },
      },
      source: "https://ui.shaduxe.com/r/styles/default/button-demo.json",
      chunks: [],
    },
    "button-installation-example": {
      name: "button-installation-example",
      type: "registry:ui",
      registryDependencies: ["button"],
      files: ["registry/default/example/button-installation-example.tsx"],
      component: safeLazy(
        () => import("@/registry/default/example/button-installation-example"),
      ),
      variants: {},
      source:
        "https://ui.shaduxe.com/r/styles/default/button-installation-example.json",
      chunks: [],
    },
    "card-demo": {
      name: "card-demo",
      type: "registry:ui",
      registryDependencies: ["card", "button"],
      files: ["registry/default/example/card-demo.tsx"],
      component: safeLazy(() =>
        import("@/registry/default/example/card-demo").then((mod) => {
          // For demo components, try to use default export first, then specific demo component
          if (mod.default) {
            return { default: mod.default };
          } else if (mod.CardDemo) {
            return { default: mod.CardDemo };
          } else {
            console.error(
              "Could not find default export or demo export in @/registry/default/example/card-demo",
            );
            return {
              default: () =>
                React.createElement(
                  "div",
                  {
                    className:
                      "p-4 text-red-500 bg-red-50 border border-red-100 rounded",
                  },
                  "Component failed to load",
                ),
            };
          }
        }),
      ),
      variants: {
        demo: {
          name: "demo",
          description: "demo variant of card",
          component: safeLazy(() =>
            import("@/registry/default/example/card-demo").then((mod) => {
              if (mod.CardDemo) {
                return { default: mod.CardDemo };
              } else {
                console.error(
                  "Variant component CardDemo not found in @/registry/default/example/card-demo",
                );
                return {
                  default: () =>
                    React.createElement(
                      "div",
                      {
                        className:
                          "p-4 text-red-500 bg-red-50 border border-red-100 rounded",
                      },
                      "Variant demo not found",
                    ),
                };
              }
            }),
          ),
        },
        variants: {
          name: "variants",
          description: "variants variant of card",
          component: safeLazy(() =>
            import("@/registry/default/example/card-demo").then((mod) => {
              if (mod.CardVariants) {
                return { default: mod.CardVariants };
              } else {
                console.error(
                  "Variant component CardVariants not found in @/registry/default/example/card-demo",
                );
                return {
                  default: () =>
                    React.createElement(
                      "div",
                      {
                        className:
                          "p-4 text-red-500 bg-red-50 border border-red-100 rounded",
                      },
                      "Variant variants not found",
                    ),
                };
              }
            }),
          ),
        },
        default: {
          name: "default",
          description: "default variant of card",
          component: safeLazy(() =>
            import("@/registry/default/example/card-demo").then((mod) => {
              if (mod.CardDefault) {
                return { default: mod.CardDefault };
              } else {
                console.error(
                  "Variant component CardDefault not found in @/registry/default/example/card-demo",
                );
                return {
                  default: () =>
                    React.createElement(
                      "div",
                      {
                        className:
                          "p-4 text-red-500 bg-red-50 border border-red-100 rounded",
                      },
                      "Variant default not found",
                    ),
                };
              }
            }),
          ),
        },
        ghost: {
          name: "ghost",
          description: "ghost variant of card",
          component: safeLazy(() =>
            import("@/registry/default/example/card-demo").then((mod) => {
              if (mod.CardGhost) {
                return { default: mod.CardGhost };
              } else {
                console.error(
                  "Variant component CardGhost not found in @/registry/default/example/card-demo",
                );
                return {
                  default: () =>
                    React.createElement(
                      "div",
                      {
                        className:
                          "p-4 text-red-500 bg-red-50 border border-red-100 rounded",
                      },
                      "Variant ghost not found",
                    ),
                };
              }
            }),
          ),
        },
        outline: {
          name: "outline",
          description: "outline variant of card",
          component: safeLazy(() =>
            import("@/registry/default/example/card-demo").then((mod) => {
              if (mod.CardOutline) {
                return { default: mod.CardOutline };
              } else {
                console.error(
                  "Variant component CardOutline not found in @/registry/default/example/card-demo",
                );
                return {
                  default: () =>
                    React.createElement(
                      "div",
                      {
                        className:
                          "p-4 text-red-500 bg-red-50 border border-red-100 rounded",
                      },
                      "Variant outline not found",
                    ),
                };
              }
            }),
          ),
        },
      },
      source: "https://ui.shaduxe.com/r/styles/default/card-demo.json",
      chunks: [],
    },
    "input-demo": {
      name: "input-demo",
      type: "registry:ui",
      registryDependencies: ["input"],
      files: ["registry/default/example/input-demo.tsx"],
      component: safeLazy(() =>
        import("@/registry/default/example/input-demo").then((mod) => {
          // For demo components, try to use default export first, then specific demo component
          if (mod.default) {
            return { default: mod.default };
          } else if (mod.InputDemo) {
            return { default: mod.InputDemo };
          } else {
            console.error(
              "Could not find default export or demo export in @/registry/default/example/input-demo",
            );
            return {
              default: () =>
                React.createElement(
                  "div",
                  {
                    className:
                      "p-4 text-red-500 bg-red-50 border border-red-100 rounded",
                  },
                  "Component failed to load",
                ),
            };
          }
        }),
      ),
      variants: {
        demo: {
          name: "demo",
          description: "demo variant of input",
          component: safeLazy(() =>
            import("@/registry/default/example/input-demo").then((mod) => {
              if (mod.InputDemo) {
                return { default: mod.InputDemo };
              } else {
                console.error(
                  "Variant component InputDemo not found in @/registry/default/example/input-demo",
                );
                return {
                  default: () =>
                    React.createElement(
                      "div",
                      {
                        className:
                          "p-4 text-red-500 bg-red-50 border border-red-100 rounded",
                      },
                      "Variant demo not found",
                    ),
                };
              }
            }),
          ),
        },
        variants: {
          name: "variants",
          description: "variants variant of input",
          component: safeLazy(() =>
            import("@/registry/default/example/input-demo").then((mod) => {
              if (mod.InputVariants) {
                return { default: mod.InputVariants };
              } else {
                console.error(
                  "Variant component InputVariants not found in @/registry/default/example/input-demo",
                );
                return {
                  default: () =>
                    React.createElement(
                      "div",
                      {
                        className:
                          "p-4 text-red-500 bg-red-50 border border-red-100 rounded",
                      },
                      "Variant variants not found",
                    ),
                };
              }
            }),
          ),
        },
        default: {
          name: "default",
          description: "default variant of input",
          component: safeLazy(() =>
            import("@/registry/default/example/input-demo").then((mod) => {
              if (mod.InputDefault) {
                return { default: mod.InputDefault };
              } else {
                console.error(
                  "Variant component InputDefault not found in @/registry/default/example/input-demo",
                );
                return {
                  default: () =>
                    React.createElement(
                      "div",
                      {
                        className:
                          "p-4 text-red-500 bg-red-50 border border-red-100 rounded",
                      },
                      "Variant default not found",
                    ),
                };
              }
            }),
          ),
        },
        underline: {
          name: "underline",
          description: "underline variant of input",
          component: safeLazy(() =>
            import("@/registry/default/example/input-demo").then((mod) => {
              if (mod.InputUnderline) {
                return { default: mod.InputUnderline };
              } else {
                console.error(
                  "Variant component InputUnderline not found in @/registry/default/example/input-demo",
                );
                return {
                  default: () =>
                    React.createElement(
                      "div",
                      {
                        className:
                          "p-4 text-red-500 bg-red-50 border border-red-100 rounded",
                      },
                      "Variant underline not found",
                    ),
                };
              }
            }),
          ),
        },
        pill: {
          name: "pill",
          description: "pill variant of input",
          component: safeLazy(() =>
            import("@/registry/default/example/input-demo").then((mod) => {
              if (mod.InputPill) {
                return { default: mod.InputPill };
              } else {
                console.error(
                  "Variant component InputPill not found in @/registry/default/example/input-demo",
                );
                return {
                  default: () =>
                    React.createElement(
                      "div",
                      {
                        className:
                          "p-4 text-red-500 bg-red-50 border border-red-100 rounded",
                      },
                      "Variant pill not found",
                    ),
                };
              }
            }),
          ),
        },
        iconLeft: {
          name: "iconLeft",
          description: "iconLeft variant of input",
          component: safeLazy(() =>
            import("@/registry/default/example/input-demo").then((mod) => {
              if (mod.InputIconLeft) {
                return { default: mod.InputIconLeft };
              } else {
                console.error(
                  "Variant component InputIconLeft not found in @/registry/default/example/input-demo",
                );
                return {
                  default: () =>
                    React.createElement(
                      "div",
                      {
                        className:
                          "p-4 text-red-500 bg-red-50 border border-red-100 rounded",
                      },
                      "Variant iconLeft not found",
                    ),
                };
              }
            }),
          ),
        },
        iconRight: {
          name: "iconRight",
          description: "iconRight variant of input",
          component: safeLazy(() =>
            import("@/registry/default/example/input-demo").then((mod) => {
              if (mod.InputIconRight) {
                return { default: mod.InputIconRight };
              } else {
                console.error(
                  "Variant component InputIconRight not found in @/registry/default/example/input-demo",
                );
                return {
                  default: () =>
                    React.createElement(
                      "div",
                      {
                        className:
                          "p-4 text-red-500 bg-red-50 border border-red-100 rounded",
                      },
                      "Variant iconRight not found",
                    ),
                };
              }
            }),
          ),
        },
      },
      source: "https://ui.shaduxe.com/r/styles/default/input-demo.json",
      chunks: [],
    },
    "switch-demo": {
      name: "switch-demo",
      type: "registry:ui",
      registryDependencies: ["switch"],
      files: ["registry/default/example/switch-demo.tsx"],
      component: safeLazy(() =>
        import("@/registry/default/example/switch-demo").then((mod) => {
          // For demo components, try to use default export first, then specific demo component
          if (mod.default) {
            return { default: mod.default };
          } else if (mod.SwitchDemo) {
            return { default: mod.SwitchDemo };
          } else {
            console.error(
              "Could not find default export or demo export in @/registry/default/example/switch-demo",
            );
            return {
              default: () =>
                React.createElement(
                  "div",
                  {
                    className:
                      "p-4 text-red-500 bg-red-50 border border-red-100 rounded",
                  },
                  "Component failed to load",
                ),
            };
          }
        }),
      ),
      variants: {
        demo: {
          name: "demo",
          description: "demo variant of switch",
          component: safeLazy(() =>
            import("@/registry/default/example/switch-demo").then((mod) => {
              if (mod.SwitchDemo) {
                return { default: mod.SwitchDemo };
              } else {
                console.error(
                  "Variant component SwitchDemo not found in @/registry/default/example/switch-demo",
                );
                return {
                  default: () =>
                    React.createElement(
                      "div",
                      {
                        className:
                          "p-4 text-red-500 bg-red-50 border border-red-100 rounded",
                      },
                      "Variant demo not found",
                    ),
                };
              }
            }),
          ),
        },
        variants: {
          name: "variants",
          description: "variants variant of switch",
          component: safeLazy(() =>
            import("@/registry/default/example/switch-demo").then((mod) => {
              if (mod.SwitchVariants) {
                return { default: mod.SwitchVariants };
              } else {
                console.error(
                  "Variant component SwitchVariants not found in @/registry/default/example/switch-demo",
                );
                return {
                  default: () =>
                    React.createElement(
                      "div",
                      {
                        className:
                          "p-4 text-red-500 bg-red-50 border border-red-100 rounded",
                      },
                      "Variant variants not found",
                    ),
                };
              }
            }),
          ),
        },
        default: {
          name: "default",
          description: "default variant of switch",
          component: safeLazy(() =>
            import("@/registry/default/example/switch-demo").then((mod) => {
              if (mod.SwitchDefault) {
                return { default: mod.SwitchDefault };
              } else {
                console.error(
                  "Variant component SwitchDefault not found in @/registry/default/example/switch-demo",
                );
                return {
                  default: () =>
                    React.createElement(
                      "div",
                      {
                        className:
                          "p-4 text-red-500 bg-red-50 border border-red-100 rounded",
                      },
                      "Variant default not found",
                    ),
                };
              }
            }),
          ),
        },
        rounded: {
          name: "rounded",
          description: "rounded variant of switch",
          component: safeLazy(() =>
            import("@/registry/default/example/switch-demo").then((mod) => {
              if (mod.SwitchRounded) {
                return { default: mod.SwitchRounded };
              } else {
                console.error(
                  "Variant component SwitchRounded not found in @/registry/default/example/switch-demo",
                );
                return {
                  default: () =>
                    React.createElement(
                      "div",
                      {
                        className:
                          "p-4 text-red-500 bg-red-50 border border-red-100 rounded",
                      },
                      "Variant rounded not found",
                    ),
                };
              }
            }),
          ),
        },
        square: {
          name: "square",
          description: "square variant of switch",
          component: safeLazy(() =>
            import("@/registry/default/example/switch-demo").then((mod) => {
              if (mod.SwitchSquare) {
                return { default: mod.SwitchSquare };
              } else {
                console.error(
                  "Variant component SwitchSquare not found in @/registry/default/example/switch-demo",
                );
                return {
                  default: () =>
                    React.createElement(
                      "div",
                      {
                        className:
                          "p-4 text-red-500 bg-red-50 border border-red-100 rounded",
                      },
                      "Variant square not found",
                    ),
                };
              }
            }),
          ),
        },
        ios: {
          name: "ios",
          description: "ios variant of switch",
          component: safeLazy(() =>
            import("@/registry/default/example/switch-demo").then((mod) => {
              if (mod.SwitchIOS) {
                return { default: mod.SwitchIOS };
              } else {
                console.error(
                  "Variant component SwitchIOS not found in @/registry/default/example/switch-demo",
                );
                return {
                  default: () =>
                    React.createElement(
                      "div",
                      {
                        className:
                          "p-4 text-red-500 bg-red-50 border border-red-100 rounded",
                      },
                      "Variant ios not found",
                    ),
                };
              }
            }),
          ),
        },
        withLabels: {
          name: "withLabels",
          description: "withLabels variant of switch",
          component: safeLazy(() =>
            import("@/registry/default/example/switch-demo").then((mod) => {
              if (mod.SwitchWithLabels) {
                return { default: mod.SwitchWithLabels };
              } else {
                console.error(
                  "Variant component SwitchWithLabels not found in @/registry/default/example/switch-demo",
                );
                return {
                  default: () =>
                    React.createElement(
                      "div",
                      {
                        className:
                          "p-4 text-red-500 bg-red-50 border border-red-100 rounded",
                      },
                      "Variant withLabels not found",
                    ),
                };
              }
            }),
          ),
        },
        withIcons: {
          name: "withIcons",
          description: "withIcons variant of switch",
          component: safeLazy(() =>
            import("@/registry/default/example/switch-demo").then((mod) => {
              if (mod.SwitchWithIcons) {
                return { default: mod.SwitchWithIcons };
              } else {
                console.error(
                  "Variant component SwitchWithIcons not found in @/registry/default/example/switch-demo",
                );
                return {
                  default: () =>
                    React.createElement(
                      "div",
                      {
                        className:
                          "p-4 text-red-500 bg-red-50 border border-red-100 rounded",
                      },
                      "Variant withIcons not found",
                    ),
                };
              }
            }),
          ),
        },
        disabled: {
          name: "disabled",
          description: "disabled variant of switch",
          component: safeLazy(() =>
            import("@/registry/default/example/switch-demo").then((mod) => {
              if (mod.SwitchDisabled) {
                return { default: mod.SwitchDisabled };
              } else {
                console.error(
                  "Variant component SwitchDisabled not found in @/registry/default/example/switch-demo",
                );
                return {
                  default: () =>
                    React.createElement(
                      "div",
                      {
                        className:
                          "p-4 text-red-500 bg-red-50 border border-red-100 rounded",
                      },
                      "Variant disabled not found",
                    ),
                };
              }
            }),
          ),
        },
        defaultChecked: {
          name: "defaultChecked",
          description: "defaultChecked variant of switch",
          component: safeLazy(() =>
            import("@/registry/default/example/switch-demo").then((mod) => {
              if (mod.SwitchDefaultChecked) {
                return { default: mod.SwitchDefaultChecked };
              } else {
                console.error(
                  "Variant component SwitchDefaultChecked not found in @/registry/default/example/switch-demo",
                );
                return {
                  default: () =>
                    React.createElement(
                      "div",
                      {
                        className:
                          "p-4 text-red-500 bg-red-50 border border-red-100 rounded",
                      },
                      "Variant defaultChecked not found",
                    ),
                };
              }
            }),
          ),
        },
      },
      source: "https://ui.shaduxe.com/r/styles/default/switch-demo.json",
      chunks: [],
    },
    "tabs-demo": {
      name: "tabs-demo",
      type: "registry:ui",
      registryDependencies: ["tabs"],
      files: ["registry/default/example/tabs-demo.tsx"],
      component: safeLazy(() =>
        import("@/registry/default/example/tabs-demo").then((mod) => {
          // For demo components, try to use default export first, then specific demo component
          if (mod.default) {
            return { default: mod.default };
          } else if (mod.TabsDemo) {
            return { default: mod.TabsDemo };
          } else {
            console.error(
              "Could not find default export or demo export in @/registry/default/example/tabs-demo",
            );
            return {
              default: () =>
                React.createElement(
                  "div",
                  {
                    className:
                      "p-4 text-red-500 bg-red-50 border border-red-100 rounded",
                  },
                  "Component failed to load",
                ),
            };
          }
        }),
      ),
      variants: {
        demo: {
          name: "demo",
          description: "demo variant of tabs",
          component: safeLazy(() =>
            import("@/registry/default/example/tabs-demo").then((mod) => {
              if (mod.TabsDemo) {
                return { default: mod.TabsDemo };
              } else {
                console.error(
                  "Variant component TabsDemo not found in @/registry/default/example/tabs-demo",
                );
                return {
                  default: () =>
                    React.createElement(
                      "div",
                      {
                        className:
                          "p-4 text-red-500 bg-red-50 border border-red-100 rounded",
                      },
                      "Variant demo not found",
                    ),
                };
              }
            }),
          ),
        },
        variants: {
          name: "variants",
          description: "variants variant of tabs",
          component: safeLazy(() =>
            import("@/registry/default/example/tabs-demo").then((mod) => {
              if (mod.TabsVariants) {
                return { default: mod.TabsVariants };
              } else {
                console.error(
                  "Variant component TabsVariants not found in @/registry/default/example/tabs-demo",
                );
                return {
                  default: () =>
                    React.createElement(
                      "div",
                      {
                        className:
                          "p-4 text-red-500 bg-red-50 border border-red-100 rounded",
                      },
                      "Variant variants not found",
                    ),
                };
              }
            }),
          ),
        },
        default: {
          name: "default",
          description: "default variant of tabs",
          component: safeLazy(() =>
            import("@/registry/default/example/tabs-demo").then((mod) => {
              if (mod.TabsDefault) {
                return { default: mod.TabsDefault };
              } else {
                console.error(
                  "Variant component TabsDefault not found in @/registry/default/example/tabs-demo",
                );
                return {
                  default: () =>
                    React.createElement(
                      "div",
                      {
                        className:
                          "p-4 text-red-500 bg-red-50 border border-red-100 rounded",
                      },
                      "Variant default not found",
                    ),
                };
              }
            }),
          ),
        },
        underline: {
          name: "underline",
          description: "underline variant of tabs",
          component: safeLazy(() =>
            import("@/registry/default/example/tabs-demo").then((mod) => {
              if (mod.TabsUnderline) {
                return { default: mod.TabsUnderline };
              } else {
                console.error(
                  "Variant component TabsUnderline not found in @/registry/default/example/tabs-demo",
                );
                return {
                  default: () =>
                    React.createElement(
                      "div",
                      {
                        className:
                          "p-4 text-red-500 bg-red-50 border border-red-100 rounded",
                      },
                      "Variant underline not found",
                    ),
                };
              }
            }),
          ),
        },
        pill: {
          name: "pill",
          description: "pill variant of tabs",
          component: safeLazy(() =>
            import("@/registry/default/example/tabs-demo").then((mod) => {
              if (mod.TabsPill) {
                return { default: mod.TabsPill };
              } else {
                console.error(
                  "Variant component TabsPill not found in @/registry/default/example/tabs-demo",
                );
                return {
                  default: () =>
                    React.createElement(
                      "div",
                      {
                        className:
                          "p-4 text-red-500 bg-red-50 border border-red-100 rounded",
                      },
                      "Variant pill not found",
                    ),
                };
              }
            }),
          ),
        },
        rounded: {
          name: "rounded",
          description: "rounded variant of tabs",
          component: safeLazy(() =>
            import("@/registry/default/example/tabs-demo").then((mod) => {
              if (mod.TabsRounded) {
                return { default: mod.TabsRounded };
              } else {
                console.error(
                  "Variant component TabsRounded not found in @/registry/default/example/tabs-demo",
                );
                return {
                  default: () =>
                    React.createElement(
                      "div",
                      {
                        className:
                          "p-4 text-red-500 bg-red-50 border border-red-100 rounded",
                      },
                      "Variant rounded not found",
                    ),
                };
              }
            }),
          ),
        },
        folder: {
          name: "folder",
          description: "folder variant of tabs",
          component: safeLazy(() =>
            import("@/registry/default/example/tabs-demo").then((mod) => {
              if (mod.TabsFolder) {
                return { default: mod.TabsFolder };
              } else {
                console.error(
                  "Variant component TabsFolder not found in @/registry/default/example/tabs-demo",
                );
                return {
                  default: () =>
                    React.createElement(
                      "div",
                      {
                        className:
                          "p-4 text-red-500 bg-red-50 border border-red-100 rounded",
                      },
                      "Variant folder not found",
                    ),
                };
              }
            }),
          ),
        },
      },
      source: "https://ui.shaduxe.com/r/styles/default/tabs-demo.json",
      chunks: [],
    },
    "pricing-one": {
      name: "pricing-one",
      type: "registry:block",
      registryDependencies: ["badge", "button"],
      files: ["registry/default/blocks/pricing-one.tsx"],
      component: safeLazy(
        () => import("@/registry/default/blocks/pricing-one"),
      ),
      variants: {},
      source: "https://ui.shaduxe.com/r/styles/default/pricing-one.json",
      chunks: [],
    },
    "pricing-two": {
      name: "pricing-two",
      type: "registry:block",
      registryDependencies: ["card", "button", "separator"],
      files: ["registry/default/blocks/pricing-two.tsx"],
      component: safeLazy(
        () => import("@/registry/default/blocks/pricing-two"),
      ),
      variants: {},
      source: "https://ui.shaduxe.com/r/styles/default/pricing-two.json",
      chunks: [],
    },
    "pricing-three": {
      name: "pricing-three",
      type: "registry:block",
      registryDependencies: ["card", "badge", "button"],
      files: ["registry/default/blocks/pricing-three.tsx"],
      component: safeLazy(
        () => import("@/registry/default/blocks/pricing-three"),
      ),
      variants: {},
      source: "https://ui.shaduxe.com/r/styles/default/pricing-three.json",
      chunks: [],
    },
    "pricing-four": {
      name: "pricing-four",
      type: "registry:block",
      registryDependencies: ["card", "badge", "button", "separator"],
      files: ["registry/default/blocks/pricing-four.tsx"],
      component: safeLazy(
        () => import("@/registry/default/blocks/pricing-four"),
      ),
      variants: {},
      source: "https://ui.shaduxe.com/r/styles/default/pricing-four.json",
      chunks: [],
    },
    "testimonial-one": {
      name: "testimonial-one",
      type: "registry:block",
      registryDependencies: ["card", "badge", "button", "separator"],
      files: ["registry/default/blocks/testimonial-one.tsx"],
      component: safeLazy(
        () => import("@/registry/default/blocks/testimonial-one"),
      ),
      variants: {},
      source: "https://ui.shaduxe.com/r/styles/default/testimonial-one.json",
      chunks: [],
    },
    "testimonial-two": {
      name: "testimonial-two",
      type: "registry:block",
      registryDependencies: ["card", "badge", "button", "separator"],
      files: ["registry/default/blocks/testimonial-two.tsx"],
      component: safeLazy(
        () => import("@/registry/default/blocks/testimonial-two"),
      ),
      variants: {},
      source: "https://ui.shaduxe.com/r/styles/default/testimonial-two.json",
      chunks: [],
    },
    utils: {
      name: "utils",
      type: "registry:lib",
      registryDependencies: [],
      files: ["registry/default/lib/utils.ts"],
      component: safeLazy(() =>
        import("@/registry/default/lib/utils").then((mod) => {
          return { default: mod.default || mod };
        }),
      ),
      variants: {},
      source: "https://ui.shaduxe.com/r/styles/default/utils.json",
      chunks: [],
    },
  },
};
